title: Chase Wiedemann
description: Business Economics PhD Candidate at Washington University in St. Louis
url: https://chasewiedemann.github.io
baseurl: ""
markdown: kramdown
permalink: pretty

exclude:
  - .RData
  - .Rhistory
  - .Rproj.user
  - EDIT_SITE.md
  - chasewiedemann.github.io.Rproj
  - build-cv.ps1
  - requirements-cv.txt
  - scripts
  - index.Rmd
  - myRender.R
  - photos
