---
title: "Learning"
---

## 8/11/2024: Making This Site

I am trying to get this site running. I'm hosting it on github pages through a Rproject. I like the simplicity of it so far, but the things I have read online have been suggesting a blogdown for larger projects. But I think I want to be the one whose doing all the background work, instead of relying on some blackbox to do it. Well, I am already relying on the blackbox of Rmarkdown, but I think I get that better.

Alright, the plan for the rest of the day is to get my municipal project onto here. What does that look like.

- You click on Projects
- Its under working projects
- you click on the title
- it takes you to the replication page (or the diary page not sure yet)
- You can get to the other pages (working paper, working slides, and replication) from that initial page

Lets go!

### Some starters

I think I want to document heavily, and to get that done, lets get a little formalism on how to do that. I imagine this isnt really where I should be doing stuff like this when working on a project, that should be on the diary page of that project, but this is like the diary of the website, so the rambling should go here. Lets say that all dated diary posts start with two hashtags and then any subsection start with 3. Lets see how this works in read time.

### Site rendering reminder
To render the site, save everything, rmarkdown::render_site(), commit and push.

### Lets try some code

```{r}
2+2
print(1+1)
```

