---
title: "Personal Site For Chase Wiedemann"
output: html_document
---

[Home](https://chasewiedemann.github.io/index.html)  \| [Research](https://chasewiedemann.github.io/_site/Projects/projects.html) \| [Teaching](https://chasewiedemann.github.io/_site/Teaching/teaching.html)  

# Hello! 

Welcome to my Personal Website. I am currently a 5th Year PhD student at Olin Business School- WUSTL. My main research focus is on how the supply of public goods can be affected by the organization of local government.  

My job market paper, which you can check out the most recent version of in Research tab above, looks at how the organization of local government affects population growth in US metropolitan areas. The main feature of organization that I examine is centralization, which can best be described in an example. Suppose we have two metro areas that are identical in every way. They are the same size, have the same population, and for the sake of clarity in the example, 100 local government employees providing public goods. The only difference between these two metros is that in the first metro, there is only one local government, and in the other there are 10 local governments employing 10 employees each. I call the first metro centralized and the second metro decentralized. 

My paper tries to answer the following question: if we were to observe these two metros after some time period while allowing migration between them and other metros, which one is more likely to have higher population growth? The existing literature provides conflicting predictions. Proponents of decentralization claim that more local governments provide competition, and that this competition will lead to a more efficient supply of public goods, which should lead to higher population growth in the decentralized MSA. On the other side of the debate, proponents of centralization argue that there may be economies of scale in local government provision and that externalities can create coordination failures. Because centralized local governments have access to economies of scale and internalize these externalities, they are more likely to have higher population growth. My results land on the side of centralization. I find that more centralized metros grew more across many time horizons. I attempt to disentangle mechanisms and find that it seems to be the coordination failures rather than economies of scale that is driving the result. 

If you ever want to reach out to discuss my research or economics in general, please do! 

Cheers!

Chase Wiedemann

c.j.wiedemann@wustl.edu