- economic activity is unevenly distyributed across space
- relative strength of the agglomeration and dispersion forces that underlie these concentration are central to a range of economic issues
- reduced form estimates need not be incariate to policy intervent (Lucas critque)
- provide an empirically relevant quantiative model to preform general equilbrium counterfcatual policy exercises
- agglomeration in these models is simply the result of exogenous local characteristics augmented by endogenous economic mechanisms

## Preferences

- homogenous vs differentiated goods
  + homogenous vs differentiated good
  + single vs multiple sectors
  + exogenous and endogenous amenities (this one is big for me)
  + fixed local factors in utility
  + common vs idosyncratic preferences 
- production technology
  + constant vs increasing reutnrs
    + new economic geogrpahy assumes increasing returns to scale
    + self reinforcing process of agglomeration, (cummulative causation)
  + exogenous and endogenous productivity differences
  + input-output linkages
  + fixed local factors in products (commercial land) acts as a congestion force
- costs of trading goods (why buy from your neighbor when the guy far away has a lower price? transportation costs)
  + variable vs fixed trade costs
  + asymmetric vs symmetric transport costs
  + geographic vs economic frictions
  + role of non-traded goods
- technology for idea flows
  + knowledge extternalities and diffusion (sharing matching and learning)
  + innovation
  
- endowments 
  + population and skills
  + spatial score and units 
  + capital and infrastucture
