
# Reading Notes

- Subcenters get agglomeration economies but with lower commuting costs for works and lower land costs for firms
- Subcenters can effect non-CBD employment density, housing prices, land rents, and population density
- Definition of a subcenter
  + Significantly larger employment density than nearby locations
  + a significant effect on the overall employment density function
- Standard appraoches use cutoff points which are arbitrary and depend on an examination of each site
- Let $D_{ij}$ be the distance between observation $i$ and a candidate subcenter site $j$, and let $DCBD_i$ represent the distance from observation $i$ to the central business district
  + Does that mean we already have to define a central business district?
- Suppose that we have $S$ candidate subcenter sites, we then estimate
$$ y_i = g(DCBD_i) + \sum_{j=1}^S (\delta_{1j}D_{ij}^{-1} + \delta_{2j}D_{ij}) + u_i $$
- $g(DCBD)$ is some non-parametric nuisance estimator
- $D_{ij}$ enters in levels and in inverse form.
- "Candidate subscenter site - the observations with highestt estimated density among all rearby sites with positive residuals- are omitted" (from the above equation)
  + What does this mean?
- Any site within a mile of the CBD is not considered a subcenter
- $g(DCBD)$ is apparently a flexible Fourier form
- How that works
  + Transform $DCBD$ into $z \in (0,2\pi)$ 
  + Estimate
  $$ g(DCBD_i) = \lambda_0 + \lambda_1z_i + \lambda_2 z_i^2 + \sum_{q=1}^Q (\gamma_q cos(qz_i) + \delta_q sin(qz_i)) $$
- How to choose candidate subcenter sites
  + Estimate on everything
  + Remove the lowest candidate site passed on t-score
  + Reestimate and repeat
  + Is this a job for LASSO?
  + Would that let me include a ton more candidate sites?
- Why are cutoff bad? Because a cutoff for LA is probably very different than a cutoff for Kansas City

## The Appendix

- Starting point is the expression
$$ y_i = m(X_i) + u_i $$
- $x_i$ is a set of explantory variables
- Take a Taylor series about $x$ to get
$$ m(x_i) = m(x) + \frac{dm}{dx}(x^*)(x_i - x), x^* \in [x_i,x] $$
- Let $\beta(x^*) = \frac{dm}{dx}(x^*)$ and $m(x) \equiv m$
- Objextive function for LWR estimator becomes
$$ Q(m,\beta(x^*)) = \sum_{i=1}^n (y_i - m - \beta(x^*)(x_i - x))^2K_i $$
- $K_i$ determines the weight given to observation $i$ in forming the prediction at $x$
  + $K_i$ is large when an observation is close to the target point $x$
- $\beta(x^*)$ are the coefficents from a regression of $K_i^{1/2}y_i$ on $K_i^{1/2}$ and $K_i^{1/2}(x_i - x)$
- $\hat m(x)$ is the predicted value at $x$
- Assume $K_i$ is estimated with a tricube kernel
$$ K_i = (1-(\frac{d_i(x)}{d_q(x)})^3)^2 \mathbb I(d_i(x) < d_q(x)) $$
- The indicator function is basically a window that gives zero weight to observations far enough away

## Getting to it

Ok. This paper has a bit more too it then I originally thought. Its pretty interesting, and honestly just applying the updated methods to it might be a contribution in its own right. I think I want to try to use the 1994 zbp as working data for this. Lets get to the summary

## Checking in

The summary is going well. I wrote the intro and then rewrote a bit. I again should probably be doing more in here, but ill probably just drop a draft into here once I have a good structure, and then live blog the editing. If I decide to do a major edit, ill try to document that in here. 

## I wish I had time codes


I think i finished writing the last section, went to go back to work, and then realized I need to change something. Im gonna contradict myself immediately. I want to talk about their data before I get into the model. The data is important because they are going to choose the set of locations that they consider in the Urban area, and I have some thoughts on that. 

## End Rant
I should probably remove that at some point. But we will see. 

## I caught something

Sites and subcenters have very different meanings. That changes a lot.

## Moving the LWR out of the appendix

I think I should move the discussion of the LWR out of the appendix and right after I describe the surface. That should make it a little more clear that the LWR is doing the first part of the definition, and the second stage is the second part of the definition.

## Conclusions

I have no idea how to conclude. Do I even want to conclude? I got what I wanted from this paper summary. Who am i concluding for? It would probably be good practice, but I think I can spend my time a bit more wisely 

## New Day

Lets get to work on the LWR section. Once I have that done, ill do a quick edit and then move on.

## Calling it
The LWR is way more confusing that I thought, but I got through it. Lets call it on this part.



