---
title: "Learning"
---

## 8/11/2024: Making This Site

I am trying to get this site running. I'm hosting it on github pages through a Rproject. I like the simplicity of it so far, but the things I have read online have been suggesting a blogdown for larger projects. But I think I want to be the one whose doing all the background work, instead of relying on some blackbox to do it. Well, I am already relying on the blackbox of Rmarkdown, but I think I get that better.

Alright, the plan for the rest of the day is to get my municipal project onto here. What does that look like.

- You click on Projects
- Its under working projects
- you click on the title
- it takes you to the replication page (or the diary page not sure yet)
- You can get to the other pages (working paper, working slides, and replication) from that initial page

Lets go!

### Some starters

I think I want to document heavily, and to get that done, lets get a little formalism on how to do that. I imagine this isnt really where I should be doing stuff like this when working on a project, that should be on the diary page of that project, but this is like the diary of the website, so the rambling should go here. Lets say that all dated diary posts start with two hashtags and then any subsection start with 3. Lets see how this works in read time.

### Site rendering reminder
To render the site, save everything, rmarkdown::render_site(), commit and push.

### Lets try some code

```{r}
2+2
print(1+1)
```

### It worked!

Lets add some more stucutre before working on the projects. I want the files system that is running this website to mimic the website. So the only thing that is going to go in the main part of the file is the index.rmd that contains the text of the front page, and the _site.yaml file that controls the formatting. Everything else goes into a folder called NavBar

In NavBar about.rmd and blog.rmd can hang out by themseleves because tthey are just static pages. But summaries and projects need additional filing. So in NavBar, there blog.rmd, about.rmd, a Projects Folder, and a Summaries Folder. We are gonna focus on the Projects folder, but it should be similar to summaries.

Within the Projects folder, we have the projects.rmd. This need to list Links to all the actual projects. Right now I have three. each with its own folder. Again lets work with MuniProject, but the others should be similar. 

We want the 4 Files in here, working paper, working_slides, replication, and diary. Lets think about what the url should look like, which will hopefully get us a little closer to a good structure.

Let ~ denote chasewiedemann.github.io. So what do we want. We want to click on ~/Projects and see a list of Projects. We Then Want to click on ~/Projects/MuniProject/ and see a the 4 ingredients. Ok. Lets get ~/Projects Working. I lied. I want to do this for the MuniProject and the GridEstimators Project as an example to make sure it works for multiple. I should probably commit.  


