---
title: "What Are We Doing Here?"
output: html_document
---

|
[Home](https://chasewiedemann.github.io/index.html) |
[About](https://chasewiedemann.github.io/Site/about.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Paper Summaries](https://chasewiedemann.github.io/Site/Summaries/summaries.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |


The goal for this site is a open and realtime look into my research.

What does that look like? I don't know. But here's what I am imagining as I start.

There are three main goals here: Documenting my Workflow, Paper Summaries, and a Realtime Blog

## Documenting my Workflow

The basic unit I'll be working on is a Project. I usually have two or three Projects going on at a time. Each Project has four main ingredients.

- Working Paper
- Working Slides
- Replication
- Min-Blog

The first two are what are typically considered academic research output, i.e. the working paper and the working slides.

The next two ingredients, in my opinion, are the most interesting. First, Replication is an informal walk through of the paper from data cleaning to creating tables and figures seen in the paper. In some ways, the replication contains more information than the academic paper, as the replication shows the step-by-step process, along with annotations discussing decisions made, of how the paper is put together. The goal of the replication is two fold. First, its a replication. Open and honest science is important. Second, the act of justifying each step in the process is helpful for me as a researcher. 

The last ingredient, the Mini-Blog, is also very interesting. While the Replication is a linear story of the paper, the Mini-Blog is a real-time look into how the Replication is made and how the Replication eventually makes its way into a working paper and slides. The Mini-Blog is very stream of consciousness and should give the reader a feel for how academic research (at least my method) actually happens. 

## Paper Summaries

I'll start this second by explaining the motivation. In my first and second years as a PhD student, my IO classes had weekly Paper Presentations due at the start of each class. After lecturing for a bit, the professor would then hand the floor over to a randomly selected student in the class to present one of the assigned papers, similar to how a discussant would present a paper at a conference. Not wanting to make a bad impression, I (and all the other students in the class) would create detailed slides on the assigned papers to be ready. 

In doing this, we learned the papers inside and out. Nothing makes you learn a paper more than needing to present it in front of your peers and advisor. The goal of the Paper Summaries page is to replicate this process. I will select papers based on my need. This could be working through an econometric method, an identification strategy, or some theory. These Paper Summaries are not meant to be Replications of those papers, but rather are used to gain additional familiarity with their content.

## Blog

Somethings that I want to learn don't fit into a set Project or Paper Summary. I also do other things (still related to economics). The catch all space for these matters is the Blog. The first entry of the Blog is actually my process of making this site. Looking at it now, you can see me struggling and (somewhat) gaining familiarity with how Github Pages work. 

The Blog also serves as a commitment device. As an example, one thing that I have become increasingly interested in is GPU computing. As you can probably tell from this site, I have a weird aversion to using black boxes. I would rather have full control over something that is ugly, than have to rely on unknown processes in order to make something pretty. There is plenty of software that implements GPU computing along with a slew of functions that would speed up my workflow considerably. I want to learn these from the ground up. The Blog is a great place for me to document this journey through a series that I plan on calling "Faster Function Friday" where I take a process that I use a lot in my work (such as inverting a matrix) and try to speed it up through the use of parallelism, RCPP code, and the GPU. 

## Closing Thoughts

If you made it this far, thanks for reading! Check out the other parts of the site to get a feel for my work. Also, please feel free to contact me. I eventually plan on making some type of interface for that through this site, but for now, shoot me an email (which can be found below) or message me on Github if you'd like to connect

Cheers,
Chase Wiedemann
c.j.wiedemann@wustl.edu

 


