---
title: "Mini-Blog"
output: html_document
---

```{r,echo = F}
base_dir = getwd()
base_url = paste0("https://",substr(base_dir,8, nchar(base_dir)))
sum_link = paste0(base_url,"/Summary.html")
miniblog_link = paste0(base_url,"/MiniBlog.html")
```

[Home](https://chasewiedemann.github.io/index.html) |
[About](https://chasewiedemann.github.io/Site/about.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Paper Summaries](https://chasewiedemann.github.io/Site/Summaries/summaries.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |

[Summary](`r sum_link`)|
[Mini-Blog](`r miniblog_link`)|

# Plan
This is a big paper. I want to first go through the authors companion paper which does the math separately from the rest, then get into the main ECMA paper

# KLR 2024: The Linear Algebra of Economic Geography Models

## Initial Reading Notes

- the world economy consists of a set of location index by $i \in \{0,\dots ,N\}$
- The economy has an exogenous supply of workers that is normalized to one $\overline l = 1$
- Each worker gets one unit of labor that is supplied inelastically. 
- Workers are perfectly mobile across location, but have idiosyncratic preferences for each location
### Consumer preference
- Every worker $v$ in location $n$ has the indirect utility function $u_n(\nu) = \frac{b_n\epsilon_n(\nu)w_n}{p_n}$
  + $w_n$ is the wage 
  + $p_n$ is the price index of the consumption good
  + $b_n$ are the amenities that are common for all workers
  + $\epsilon(\nu)$ is a idosyncratic amenities preference draw that is specific to each worker $\nu$ and location $n$
- The price index is of the form $p_n = \left(\sum_{i=1}^N p_{ni}^{1-\sigma})\right)^{1/1-\sigma},\sigma>1$
- The idiosyncratic amenities draw are independent for each worker and location from the forllowing distribution $F(\epsilon) = exp(-\epsilon^{-\kappa}), \kappa >1$
  + The scale is normalized to one, as it is isomorphic to $b_n$ (the common amenities of location $n$)
  + $\kappa$ regulates dispersion of idiosyncratic amenities, which in tern determine migration elasticity, ie how responsive the population share of each location is to real wages $w_n$
### Production Technology
- Goods are produced with labor according to a constant returns technology and under the conditions of perfect competition
- Iceberg variable costs of trade: $\tau_{ni}$ must be shipped from $i$ to $n$ in order for one unit to arrive
- Cost to consumer in $n$ of purchasing the good produced in $i$ is $p_{ni} = \frac{\tau_{ni}w_i}{z_i}$
  + $z_i$ is the productivity in location $i$
  + Prodctivity on the shippers end decreases price at the recievers end
  + $z_i$ is exogenous, but apparently easy to endogenize with agglomeration economies that let productivity in each location increase with its own population of the population of immediate neighbors
### General Equilibrium
- GE is referenced by the vectors of wages and population shares in each location $\{\vec w, \vec l\}$ ($2\times N$ Matrix)
- Conviniently, we get $2\times N$ equilbrium conditions from the goods market clearning and population mobility.
- Goods market clearing
  + Income in each location equals expenditure on the good produced in that location $w_il_i = \sum_{n=1}^N s_{ni}w_nl_n$
  + $s_ni$ is the share of expenditure of importer $n$ on exporter $i$ 
  + From the CES Demand and the Production technology we get $s_{ni} = \frac{[(\tau_{ni}w_i)/z_i]^{-\theta}}{\sum_{m=1}^N [(\tau_{nm}w_m)/z_m]^{-\theta}}$
  + $\theta \equiv \sigma-1$ and is the trade elasticity
  + We then normalize the income of all location to 1: $\sum_{i=1}^N w_il_i =1$
  + The choice of distribution for $\epsilon$ gives us the probability a worker chooses to live in location $n$, and there for the number of workers in location $n$ as $l_n = \frac{(b_nw_n/p_n)^\kappa}{\sum_{h=1}^N (b_hw_h/p_h)^\kappa}$
  + Expected utility then must be the same across all locations and is given by $\overline u = \Gamma(\frac{\kappa -1}{\kappa})\left[\sum_{h=1}^N (b_hw_h/p_h)^\kappa \right]^{1/\kappa}$
  + Not normalize, endogenous in the model
### Some intuition
- Each locaion faces an upward slipping supply function for workers
  + locations have to offer a higher real wage relative to other location in order to attract a larger share of the population
- Locations that offer higher real wages attract workers with lower realization for idiosyncratic amenities
  + in english that means... Pittsburg (bad amenities) has to pay more?
- The frechet distribution allows for the wage to be exactly offset b the composition effect of lower average amenities
  + I hate this assumption, San Fran has the highest amenities and the highest wages
- Along with the exogenous productivity assumption, the dispersion force from worker idiosyncratic preferences ensures the existance of a unique eq distribution of wages and population shares across locations.
### Freind-Enemy Exposure Measures
- going to consider small productivity shocks, holding constant amenities $dlog b_i =0$, bilateral trad costs $dlog\tau_{n} =0$ amd the total population of the economy $dlog \overline l =0$
- Totally differntiate the goods market clearning codition, $w_il_i = \sum s_{ni}l_iw_i$ to yield $d logw + dlog l = T(dlog w +d logl) + \theta(TS-I)(dlog w - dlog z))$
  + S is a matrix of $s_{ni}$, the share of importer $n$'s expenditure on exporter $i$
  + T is a matrix with $T_{in} = S_{ni}\cdot \frac{w_nl_n}{w_il_i}$, exporter $i$'s income from inporter $n$
- Chanes in the total income of a location of the left hand of this equation (including both change in wages and change in popilaion) depend on a market size effect (first term on the right hand side) and a cross-substiution effect (second term on the right hand side)
- Market-size effect capture the fact that an increaes in the income of market $n$ on the right hand side increase the income of location $i$ on the left hand side by and amount that is determined b the share of location $i$ income from market $n$ given by $T{in}$
- The cross substitution effect depends on the product of the income and expendtireue share martixes $TS-I$
  + for $i\neq n$ the sum $\sum_{h=1}^N t_{ih}s_{hn}$ captures the overall competitive exposer of location $i$ to location $n$ through each of their common markets $h$ weighted by the importance of market $h$ for country $i$'s income ($t_{ih}$)
  + As competitiveness of location $n$ increases, as measured by a decline in its wage relative to its productiveity ($dlogwn - dlogz_n$) consumers in all makerts $j$ substitute towards location $n$ and awa from other locations $i\neq n$
  + What does wage being equal to prductivity tell us?
  + This substitution effect reduces income in location $i$ and reaises it in location $n$ 
  + The CES import demand sstem imposes that the magnitude of this cross-substitution efect in market $h$ depends on the trade elasticity $\theta$ and the share of expenditure in market $h$ on the goods prodced in location $n$
  + this means that consumers in market $h$ increase the expenditure share on county $n$ by $10s_{hn} and lower the expendtire share on county $i$ by $s_{hn}$ This is just logit. They have rediscovered logit. 
- Now was are going to totally differentiate the location choice probabilities $l_n = \frac{(b_nw_n/p_n)^\kappa}{\sum_{h=1}^N (b_hw_h/p_h)^\kappa}$ and get $dlog l = \kappa(I-1l')[dlog w - S(dlog w- dlogz)]$
- The ppulation share of a location is increasing in its wage.
- the population share is decreasing in its price index.
- Now we are going to totally differentiate expected utility $\overline u = \Gamma(\frac{\kappa -1}{\kappa})\left[\sum_{h=1}^N (b_hw_h/p_h)^\kappa \right]^{1/\kappa}$ to get $d log \overline u = l' [d log w - S(dlog w - dlog z)]$
- So now if we shock one of these equations, its gonna ripple through the others
  + We might shock the producitivity, which would then change the distribution of wages, which would change the population share, which changes the income, which of course then gets fed back into wages through the market size effect. 
- We are now going to link the equations by using the income normalization and rewriting the goods market clearing condition as $I+Q)(dlog w + d log l) = T(d log w + dlog l) + \theta(TS-I)(dlog w - dlog z)$
  + $Q$ is a $N\times N$ matrix with the nominal income row vector $q'$ stacked $N$ times and because of our normalization, we have $Q(dlog w +dlog l) = 0$
  + A root we can find
- We can then substitue the changes in population shares into the goods market clearing and using the common level of expected utilit , we obtain the flosed for expresion for the elasticity of wages in each location with respect to productivity shocks in all loaction $d log w = W dlog z$ 
  + $W$ is the friend-enemy matrix of bilarter wage exposure to productivity shocks
  + $W = -(91+\kappa)I- \kappa1l' - V)^{-1}V$
  + $V = \kappa(I-1l') + (I-T+Q)^{-1}\theta(TS-I)

## Thoughts after the first reading
Is this logit? The restricted substitution patterns make it seem so. I don't think that my summary of the KLR 2023 needs this, but I imagine that the math is going to be helpful. In the worst case, I've seen their notation now and will hopefully be a bit faster in the main paper.

# KLR 2023
lets go

- centeral question: understand the response of the patial distribution of economic activety to fundamental shocks, such as changes in productivity. (thats a counterfactual)
- responce to shocks is graduaal beacuse migration friction cause the tiebout hypotheiss to move slow, and capital takes time to build
- challenge: forward looking capital investments with population mobility
- investment and migration decisions in each location depend on one another, and decisions in all locations in all future time periods. (giant state space)
- They are going to give us a tractable framework for incorportating foward-looking investment into dynamic descrete choice migration model that tackles the issue of a giant state space
- Second, through linearization, they obtain closed form solutions for the economies transition path in terms of an impact matrix that captures the initial impact of shocks and a transition matrix that governs the updating of state-variarbles.
- They show that the repsonce of the economy to any shock tofundaments can be characterized in terms of the eigenvalues and vector of the transition matrix.
- With this they are able to show that capital accumulation and migration dynamics play a centreal role in the observed decline in the rate of income convergence accros US states and the persistent and heterogenous impact of shocks.
- To show their new stuff, they use standard and simple models from the literature
  + Single sector Armington (1969) model of trade with constant elasticity gravity equation fro trade
  + constant elasticity dynamic discrete choice model of migration from CAliendo, Dvorkin, \& PArro (2019), which gives us a constant elasticity gravity equation for migration
  + textbook macro specification for capital accumulation where agents choose consumption and investment to maximize intertemporal utility subject to an intertemporal budget constraint
  + The main simplifying assumption is to draw a distriction between workers and landlords, like Moll (2014), where morkers make forward-looking migration decisions, but do not have access to an investment technology and live "hand to mouth". LAndlords are geographically immobile, but have access to an investment technology in local capital such as buildings and structures, and make forward looking capital accumulation decisions with respect to that capital
- the model allows for many locations that differ in productive and amenities, and a rich geography of bilateral trade and migration costs.
- They are going to show how to derive analytical conditions for the existence and uniqueness of equilibirum
- The eq only relys on the structural parameters such as agglomeration and dispersion forces which are invarient with respect to the initial conditions.
- The exact-hat algebra can let us take any point on the trasition path, change the the fundamentals, and then solve for the counterfactual transition path.
- Linearizing the model gives us a closed form solution for the eoncomies transtion path in terms of the impact and transition matrices. These matrices depend solely on trade and migration shares that are observed in the data and the structural paramters
- Eigendecompostion of the transition matrix shows that the dynamic responce of the state variables to any empiralcal shock to productivity and amenities can be expressed as a linear combination of its response to what they call eigenshocks
  + shocks to the fundamentals for which the initial impact on the capital and labor state vairavles correspons to an eigenvector of the transition matrix. 
- Eigenshocks have three key properties
  + computable from the observed data
  + speed of convergence to steady state for an eigen shock depends solely on the associated eigen value, allowing for sharp characterization of the determinates of speed of convergecne
  + we can revoer loadings of any empirical shock to fundamentals on these eigenshocks from a linear projection of the empirical schocks on the eigenshocks, which allows them to use the framework to understand the impact of epmirical shocks.
- They apply their framework to the determinants of income convergence across US states from 1965 to 2015. 
- The tractablity of their approach allows for a large number of extensions and generalizations including agglomeration forces in production and residential decsiion. They show that the model works for a large class of trade and interal competition models.
- Who do they cite?
  + Economic Geography - Krugman 1991 and Fujita, Krugma and Venables 1999
  + dynamic discrete choice models of migration: artuc, chaduhuri and mcLaren 2010, Caliendo and Parro 2020, allen donalson 2022, but the big one is above
  + dyanmic models of capital accumulation: Aderson, Larch, Yotov 2015, Eaton Kortum Neiman and Romalis 2016, Alverex 2017, ravikumar, santacreu and sposi 2019

## The model
- $N$ Locations indexed by $i$
- Discrete time indexed by $t$. 
- Two types of infinitely lived agents
  + workers
  + landlords
- Workers are endowed with one unit of labor that is supplied inelastically and are geographically mobile subject to migration costs. Wroders do not ahve access to any investmetn technology, so they live hand to mouth as in Kaplan Violante (2014)
- Landlords are geographically immoble and own the capital stock in their location. 
- They make forward lookign decsiions over consumption and investment in this local stock of capital. 
  + We should be thinking of this capital as buildigns and strucures that are geographically immobile once installed and depreciate at a constant rate $\delta$
- The endogenous state variables are the population and capital stock in each location. 
- the key location characteeristics that determine the spatial distribution of economic activity are the sequences of productivity $z_{it}$, amenities $b_{it}$, bilateral trade costs $\tau_{nit}$, and bilateral migration costs $\kappa_{nit}$. 
- We normalize the total population across all location to be equal to 1 in each period. This allows us to take $l_{it}$ as a population market share

### Production
- at the begining of each period $t$, the economy inherits in each location $i$ a mass of workers $l_it$ and a capital stock $k_it$. 
- firms in each location use labor and capital to produce out put $y_{it}$ of the variety supplied by that location. 
- Production is assumed to occur under conditions of perfect competition and subject constant returns to scale technology
$$ y_{it} = z_{it}(\frac{l_{it}}{\mu})^\mu(\frac{k_{it}}{1-\mu})^{1-\mu}, 0 < \mu <1 $$
- Impose inceberg variable trade costs, such that $\tau_{nit}>1$ units of a good must be shipped from location $i$ in order for one unit to arrive in location $n$. 
- profit maximization implies the cost to the consumer in location $n$ of sourcing good produced in location $i$ depends solely on these iceberg trade costs and constant marginal costs 
$$ p_{nit} = \tau_{nit}p_{iit} = \frac{\tau_{nit}w_{it}^\mu r_{it}^{1-\mu}}{z_{it}} $$
Where $p_{iit}$ is the free on board price of the good supplied by location $i$ before trade costs
- Normalize total labor income of all location $\sum_{i=1}^N w_{it}l_{it} = 1$
### Worker consumption
- workers preferences in each period $t$ are the standard ARmington model of trade with constant elasticity of subsitution
- Workers spend wage income on products from different location to maximize utility in each period
- flow utility of a worker in location $n$ in period $t$ depends on amenities $b_{nt}$ and the consumption index $c^w_{nt}$ defined over the variety of products given as 
$$ u_{nt}^w = b_{nt}c^w_{nt}, c_{nt}^w = \left[ \sum_{i=1}^N (c_{ni}^w)^{\theta/(\theta+1)}\right]^{(\theta+1)/\theta}, \theta = \sigma -1, \sigma >1 $$