---
title: "Projects"
output: html_document
---

|
[Home](https://chasewiedemann.github.io/index.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |


## Works in Progress 

- [Estimating Effects of Municipal Structure on Urban Area Preformance Using Firm Expectations](https://chasewiedemann.github.io/Site/Projects/MuniProject/Replication.html)
  + Decomposes The Effect of Municipal Structure on Firms Expectations for Urban Area Success
- [Market Failures in Municipalities](https://chasewiedemann.github.io/Site/Projects/Muni_Market_Failures/Replication.html)
  + Examines Sources of Market Market Failure in Municipalities 
- [Unobserved Hetrogenity On Grids](https://chasewiedemann.github.io/Site/Projects/FKRB/Replication.html)
  + Examines Identification and Estimation of Unobserved Heterogeneity through the Use of Grids
- [Deep Dive on Generating Random Vectors](https://chasewiedemann.github.io/Site/Projects/mvrnorm/mvrnorm_deep_dive.html)
  + Examining How R Generates Random Vectors with Covariance


## Paper Summaries

- [McMillen (2001): Nonparametric Employment Subcenter Identification](https://chasewiedemann.github.io/Site/Projects/McMillen_2001/Summary.html)
  + Identifying Employment Subcenters Using a Two Stage Non-Parametric Procedure (LWR and Flexible Fourier)
  
