---
title: "Summary"
output: html_document
---

```{r,echo = F}
base_dir = getwd()
base_url = paste0("https://",substr(base_dir,8, nchar(base_dir)))
sum_link = paste0(base_url,"/Summary.html")
miniblog_link = paste0(base_url,"/MiniBlog.html")
```

[Home](https://chasewiedemann.github.io/index.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |

All code was original produced by the authors and credit goes to them for putting this all together.

*Kleinman, B., Liu, E. and Redding, S.J. (2023), Dynamic Spatial General Equilibrium. Econometrica, 91: 385-424. https://doi.org/10.3982/ECTA20273*

## Technical Code Review

Here we will examine the code from Kleinmann Liu \& Redding (2023), specifically the section that produces Figure 5. Figure 5 shows the productivity and amenitiy shocks by state. In doing this review, we wish to learn more in-depth about how their model calculates productivity and amenity levels throughout time. The code was accessed through this [link](https://onlinelibrary.wiley.com/doi/full/10.3982/ECTA20273)

### The Code

Following the link above leads to a downloadable zip file found under the "Supporting Information" Tab. Within the zipfile, the code we will be examining is filed under `ModelSingleSector/code/`

