- dynamic ologopoly modles allow us to study the effects of a government policy on technological progress and on industry structure
- long-run effects can dwarf the short run static effects 
- recent work was made possible by BBL 2007 Pakes Ostrovsky and Berry 2007, Aguirregabiria and Mira 2007, Pesendorfer and Schidt Dengler 2003
  - do not need to compute MPE
- still need to compute equilibrium in counterfactuals
  + so modeling choices are limited due to this
- oblivious eq (OE) each firm is assumed to make decisions based only on its own state and knowledge of the long run industry state, ignore current information about competitors states
- computation time is not linked to the overall number of firms in the industy
- OE has the weakness that it is not applicable to concentrated industries
- partially oblivious eq (POE) allows for a set of strategically important firms
- OE is a POE with no dominant firms, MPRE is a POE with all dominant firms
- POe has a behavior interpretation as firms would follow strategies that are functions of more than a handfull of competitor firms
- In POe dominiant firms generally invest more than fringe firms, and this lead to them being dominant most of the time
- POe is not as theoretically clean as OE
  + Dpes not allow for frims to transition from fringe to dominant or vice versa
  + opens open the question of which firms to label as dominant
  + as firms strategies depend on the values of the dominant firms states, but firms have only incomplete knowldege of the current overall industry state because they only track the dominat firms states. Thus the unknown current values of the firmge firm states are partially determined by past values of the dominant firms states, which implies that past value s of the dominant firms states might potentially be useful in predicting the current fringe firm states. Furthermore in principle an infornite histroy might be useful. In the implementation of POIE firms strategies are assumed to be fuinction of finite and short histories
- Pakes and Mcguire 2001 propose solvign the game with a stochastic approximation algorithm (experience based eq)
- Dprasze;slo amd Judd 2012 use continuous timoe which reduces the comp cost at each state point
- Farias Saure and Weintraub 2012 use approaximate dynamic programming which approximates the value function by basis functions
- The approach in POE is to restrict the strategies of firms or equivalently limiting their information set
  + not as strategically rich as full MPE
- ifrach and weintraub 2014 builds upon OE with firms strategies beging functions of dominant firms states and summary statistics of fringe firms, and dominant firms areise endogenously in eq
  + transition kernel of the state variables is not MArkov, and simulation is required to estimate it
- index time by $t$
- index firms by $i$
- Set of indeces of incumbent firms at time $t$ is denoted $S_t$
- number of incumbent firms is $n_t$
- firm geterogeneity is reflected throguh firms tates $x_it$, think quality
- industry $s_t$ is a vector that list for each possible qua;ioty level the number of incumbant firms in that level in period $t$
- $\overline S$ is the set of all possible $s_t$
- $s_{-it}$ is the competitors of $i$, ie the number of firms that share a quality level 
- In each period, firms observed $\phi_{it}$ as a sell of value
- if the sell off value exceed the value of continuing in the industry,, then the firms can exit
- if a firm decides to stay, it invests $\iota_{it}$ and the firms state transitions to $x_{it=1} = x_{it} + h(\iota_{it},\zeta_{it})$
- $\zeta$ is an idiosyncratic shock capturing the uncertainty in investment
- each unit of $\iota$ costs $d(\iota)$
- in each period, the following events occur in order
  + firms ovserve sell off value and makes exit and investment decsiions
  + firms enter and pay entry cost of $\kappa$
  + Incumbants compete in the spot market
  + Exiting firms exit and recieve their selloff values
  + investments matrure, new quality is determined, enterants enter, and the industry takes on a new state $s_{t+1}$
- What we need to specify/estimate parameters for
  + profit function
  + sell off value distribution
  + investment impact function
  +  investment uncertainty distribution
  + entry cost
  + discount factor
- a good example is logit demand with single product firms, constant marginal cost, and a static equilbrium that is nash in prices
- assumptions on model primitives
  + $\pi(s,x)$ is increasing in $x$
  + $\pi() \geq 0$
  + $\phi$ the sell off is iid, finite, and positive
  + $\zeta$ is iid and independent of $\phi$
  + $ h(\iota,,)$ is increasing in investment
  + changes in quality have positive probability
  + investment and quality changes are bounded
  + quality chagnes are continuous
  + transitions are unique investmnet choice admissible
    -  ensures that a unique solution to the firms investment decision problem. 
  + entryt is a poisson random variable
  + $\kappa$ is large enough that you cant just enter to get scrap payoffs
- let the number of entering firms at $s_t$ be $\lambda(s_t)$
- Equilbrium is based of symmetric MPE
- incumbent firms follow a Markeove investment and exit strategy that is self generating in the sense of being optimal wehen all competitor firms follow the same stategy
- investment strategy $\iota(x_it,s_{-it})$
- Exit strategy $\rho(x_it,s_it)$
  + form of a cut off rule, ie exit if $\phi > \rho$
- value function $V(x,s|\mu',\mu,\lambda)$ when i play $\mu'$, my compeitors play $\mu$ and entry is governed by $\lambda$

$$ V(x,s|\mu',\mu,\lambda) = E_{u',u,\lambda} (\sum_{k=1}^{\tau_i} \beta^{{k-t}}(\pi(x_{ik},s_{-ik}) - d\iota_{ik}) + \beta^{\tau_i-t}\phi_{i,\tau_i} | x_{it} = x, s_{-it} = s) $$
- $\tau_i$ is the expected time that firm $i$ exits
- Eq comproses of an investment exist strategy $\mu = (\iota,\rho)$ and an entry rate function $\lambda$ such that
  + $sup V(x,s|\mu',\mu,\lambda) = V(x,s|\mu,\lambda)$
  + entrants have zero expected profits of the entry rate is zero or both
  
$$ \sum_{s \in \overline S} \lambda(s)(\beta E_{\mu,\lambda} V(x^e,s_{-i,t+1}|\mu,\lambda)|s_t = s) - \kappa) = 0 $$ 
## Partially oblivious eq

- POE have strategies that a function of the firms own state (quality and dominant or not), and the states of dominant firms
- neccessary to model firms beliefs about the values of fringe firms states
- in OE all firms are fringe
- in POE, fringe firms also know the state of the dominatn firms and follow straegies that are function of the dominant firms states
- the distribute of frind firm states at any time depends on all past values of the dominant firm states
- computing expectation this was is unrealistica as a model of behavior.
- computationall impractical. 
- restrict firms to predict fringe firm states using a finite set of statistics that depend on the past history of the dominatn firms state. 
- let $y_t$ be a vector that represent the states of the dominat firms at time $t$. 
- let $w_t$ represent a finite set of statitics that depend on the history of realizations of dominat firms states, where $w_t(1) = y_t$
- the other state variables $w_t(k)$ allow firms to incorporate additional information about the history of realization of the dominat firms state.
- Let $\mathcal M$ and $\Lambda$ be the set of partially oblivous investment and exit strategies and entry rate function

- firms beleive that the fringe firms state is equalt to the expected fringe firms state conditonal on the current value of the dominant firm state statistics $w_t$
- let $f$ represent the state of the finge firms, ie it is a vector of fringe firm quality levels

### CW





