---
title: "Mini-Blog"
output: html_document
---
```{r,echo = F}
base_dir = getwd()
base_url = paste0("https://",substr(base_dir,8, nchar(base_dir)))
wp_link = paste0(base_url,"/WorkingPaper.html")
ws_link = paste0(base_url,"/WorkingSlides.html")
rep_link = paste0(base_url,"/Replication.html")
miniblog_link = paste0(base_url,"/MiniBlog.html")
```

[Home](https://chasewiedemann.github.io/index.html) |
[About](https://chasewiedemann.github.io/Site/about.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Paper Summaries](https://chasewiedemann.github.io/Site/Summaries/summaries.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |

[Working Paper](`r wp_link`)|
[Working Slides](`r ws_link`)|
[Replication](`r rep_link`)|
[Mini-Blog](`r miniblog_link`)|

# Inital Post

Created the subdirectories along with a template. Want to make sure this will all work!

# Getting to work

I have the site running where I want, lets get to some actual work. What do I want to do to start the replication? There should obviously be some sort of explanation about what I am doing before I get into code. So maybe I get some back ground on the Alonso Muth and Mills cbd model, bring in some stuff about the polycentric theory, and then talk about static subcenter identification. I can then point out where I think the issues are with that, and introduce dynamics into the identification problem. 

Once thats all done, I think I want to try using the API. Thats probably not something I would have done if I wasnt doing this on the page, but isn't that the point of the page?

## Some Thoughts

The replication is getting pretty stream of consiousness as well. That was supposed to be reserved for the blog and mini-blog. But I think I am figuring out the difference. The Replicaiton can be editted, while the blogs cannot. So while I can go back and edit the absolute garbage that is in the replication page right now as I get a better idea of the direction of the project, I should be keeping the blog and mini-blogs as a constant stream. I also realized that I need to do more site editing. But Ill describe that in the big blog. 

## Were Back, and a Couple more Thoughts
This is very early stage, and this is the first mini-blog so bear with me. Similar to how I had header rules for the big blog, I'm gonna need some here as well. Maybe each day is a single hash, then topics are a double, and then thoughts about that topic are triples. Lets go with that

## Actual Work: Skipping to some data
I want to get some progress done. So we are gonna start getting the census api figured out to get the ZCBP stuff into our replication file. 

Ill update how that goes. Lets go.

### Jumping around
I through out some ideas about making my model based on the unobtainable Business Registrar in the Census, and how we need to do basically summary statistics from that because thats all we observe. Its a good idea but I feel like Im jumping around. Im gonna finish that thought and then get back to the data work.

### Style Question to Think about

When I working with code, I am already annotating with the text around it. What should my code comments be? Probably flags that I can easily reference in the text instead of typing out what I'm doing in a comment. Or maybe a mix of both. If i dont want to talk about it in the text, but it is somewhat noteworthy, Ill give it a comment, if can go without, it goes without, and if I want to talk about it in the text, Ill make some obvious flag and reference that flag in the text. Perfect. Lets go. to Lunch, but then were back





