---
title: "Replication"
output: html_document
---
```{r,echo = F}
base_dir = getwd()
base_url = paste0("https://",substr(base_dir,8, nchar(base_dir)))
wp_link = paste0(base_url,"/WorkingPaper.html")
ws_link = paste0(base_url,"/WorkingSlides.html")
rep_link = paste0(base_url,"/Replication.html")
miniblog_link = paste0(base_url,"/MiniBlog.html")
```

[Home](https://chasewiedemann.github.io/index.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |

[Working Paper](`r wp_link`)|
[Working Slides](`r ws_link`)|
[Replication](`r rep_link`)|


# Abstract

# Introduction

The geographic structure of the economy can be seen as a self-replicating system. At the highest level, we consider the global economy, where large economic groups like the EU or NAFTA compete. If we zoom in one level, this process repeats. Instead of looking at global competition, we now focus on how countries within these groups compete against each other. This layered competitive structure creates complex incentives and welfare calculations: a country’s success depends not only on its own performance, but also on the performance of its entire economic group. Using "Invisible Hand" arguments from the First Welfare Theorem, we can rely on competition among countries to provide a Pareto efficient outcome. Relying on the Second Welfare Theorem allows for selection of the most efficient Pareto outcome for the benefit of the whole group. Importantly, these assumptions hold true only if there are no market failures.

This paper deepens the scope of this system by two levels. Moving down one level in scope shifts the focus from competition between countries in a global economy to competition among urban areas within a country. One deeper level in scope, our focus, is on competition between municipalities within an urban area. Without market failure, competition between municipalities leads not only to a Pareto efficient outcome for each municipality, but for the most efficient allocation for the urban area as a whole. However, specific details regarding municipal competition make market failures not only possible, but likely. 

These likely market failures motivate the policy prescription investigated in this paper, municipal mergers. To clearly see these market failures, we make two key assumptions. First, we assume that there are no market inefficiencies, except potentially at the municipal level. This allows us to treat the outcomes from competition among urban areas, and competition at higher levels, as the result of perfect competition and therefore Pareto efficient. Second, we assume that given market failures in the municipal level, we are close and below the Pareto optimal allocation that would exist without any market inefficiencies. This allows us to consider the effects of interventions as full rather than partial equilibrium. Stated plainly, these assumptions allow us to examine interventions that can increase welfare in a specific urban area, without the necessity to compute best-responses from other urban areas. As motivation for these assumptions, we later discuss why the market failures suspected under municipal competition would not be present at higher levels of competition. Further, we discuss the political economy ramifications of such assumptions within our specific application of municipal mergers in the St. Louis Metropolitan Area. 

Possible market failures in municipalities stem from four broadly defined sources. First, market failures can occur due to the spatial nature of municipal competition. This refers to the fact that municipalities reside on a geography and operate under restrictions implied by that geography. Second, political constraints on municipalities can be a source of market failure. These constraints include a legally mandated balanced budgets, fixed jurisdictional boundaries, and rare municipal exit. Third, market failures can also be a result of dynamics, as irreversible investment decisions made at one point in time could have been optimal, but due to changes in technology or preferences now contribute to a market failure.  Finally, market failures can result from imperfect competition between municipalities that affords privileged municipalities, in terms of size or resources, a form of municipal market power.

As stated above, this paper investigates municipal mergers, or the process of merging one or more political entities into one, as a possible policy intervention to mitigate these market failures. Such a heavy handed policy instrument is shown to be needed through a process of elimination. Alternative policy interventions, such as transfers, removing the restriction of balanced budgets, collectively set property tax rates, and allowing municipal exit and expansion, are examined. We contend that these alternatives not only fail to address all sources of market failure, but can often lead to new sources of inefficiency. 

Municipal mergers are not a new concept in policy debates surrounding municipalities. Advocates of municipal mergers rely on the expected benefits from access to greater economies of scale and more effective regional planning. Detractors counter these claims with the perceived negative effects of decreased constituent attachment to the political process and increased costs stemming from bureaucracy. A large academic literature has tried to add to this debate by investigating past municipal mergers. This literature has lead to mixed results. The difficulty in extracting policy implications from past mergers are both empirical and theoretical. 

On the empirical side, examining past mergers presents two main challenges. First and foremost, municipal mergers are relatively rare events, making empirical estimates drawn from them subject to high variance. Second, mergers happen in an array of different cultural, political, and historic contexts, making external validity a concern when extrapolating results into a specific context. Combining these two observations, along with the observation that a municipal merger can be viewed as a strong change to the competitive environment, leads to the Lucas Critique, coefficients estimated in the reduced form are not invariant to policy changes and therefore can mislead policy prescriptions. 

On the theory side, we are presented with three main challenges. First, municipal mergers do not occur in a vacuum, but rather inside a larger urban area. A counterfactual merger changes the incentives and the competitive environment for all residents, firms, and municipalities located in the urban area. Second, dynamics in the form of forward-looking agents play an immense role as the counterfactual merger can induce changes to established investment patterns, which allows for the rectification of the effects of past, previously irreversible, investment decisions. Third, a workable measure of welfare is often difficult to establish in these settings, making comparative statics or the answers to normative questions about pursuing municipal mergers difficult to come by.

If the goal is to extract normative policy prescriptions regarding mergers, these issues must be addressed. The proposed solution in this paper is to embed the framework of municipal mergers into a structural model of an urban area. Just as counterfactual mergers between competitive firms in a product market have been examined, we can examine counterfactual mergers of competitive municipalities in the market for residents and firms. This approach not only allows us to quantify the effects of the possible market failures, but allows us to estimate how municipal mergers would mitigate these effects. 

A structural approach allows us to address both the theoretical and empirical issues of past studies. Starting with the theoretical, as a model of the entire urban area, the incentives of municipalities, residents, and firms are endogenous. This allows agents the opportunity to re-optimize after the counterfactual merger, which lets the new competitive environment of the urban area determine counterfactual allocation decisions. On the empirical side, the structural model allows us to simulate a merger without the need to have observed a merger in the data. As the incentives of our agents are recovered as model primitives, the outcome of a counterfactual merger is just the result of these agents optimizing in a new competitive environment. 

Two main economic primitives of the model will drive the estimates and policy prescriptions of the model. First, primitives governing the municipal production function will determine how a municipality will be able to map their tax revenue into municipal quality. Following the literature, we expect to find an inverted U-shaped curve, as municipalities trade off between economies of scale and congestion effects. The peak of such a curve can be thought of as the "optimal" municipal size, which guides the selection of merge partners. Second, substitution patterns for both residents and firms will dictate how agents re-optimize post-merger. To preform the counterfactual merger simulation, these two primitives must be both stable and policy invariant. 

The remainder of this paper is as follows. Section 2 explores the sources of municipal market failures, examines the alternative policy interventions, and examines the previous literature on municipal mergers. Section 3 reports reduced form evidence of market failures at the municipal level. Section 4 introduces the dynamic model of the urban area. Section 5 examines our data and gives additional details regarding our application to the St. Louis Metropolitan Area. Section 5 presents the estimates and robustness checks on the model including estimates of the effects of municipal market failures. Section 6 examines various counterfactual mergers in the St. Louis Metropolitan Area and reports estimated welfare effects of such counterfactual mergers. Section 7 concludes.

# Municipal Market Failures, Alternative Policy Interventions, and Municipal Mergers

In this section, we first discuss how municipal mergers may come from four potential sources: spatial, political, dynamics, and imperfect competition. These sources are not distinct, but rather play off one another and often exacerbate market inefficiencies. We then discuss why the investigated market failures are less likely to occur in higher levels of of geographic competition with a focus on urban area competition. Next, we examine alternative policy interventions, namely transfers, removing the restriction of balanced budgets, collectively set property tax rates, and allowing municipal exit and expansion. We see that these alternative policy prescriptions often do not address all sources of market failure. In particular, none of these alternatives address concerns over dynamics or imperfect competition. Further, we examine how the implementation of these alternative policy prescriptions are likely not only politically or geographically unfeasible, but would create new sources of market failure. Finally, we discuss the past literature on municipal mergers, gleaning information that can help motivate the selection of counterfactual mergers in section 6.  

## Municipal Market Failures


Certain institutional details regarding municipalities suggest that market failures are likely to occur. First, municipal budgets are legislatively enforced to be balanced. Second, municipal boundaries are generally fixed at the time of incorporation and rarely change. Third, municipalities typically do not have the option to exit the market. Finally, municipalities can only enter at the outskirts of an urban area, which causes existing municipalities to become "landlocked". We consider two leading examples to center the discussion of municipal market failures around.

First, consider a high-quality municipality. Its appeal attracts firms and residents (refered to jointly as inhabitants), expanding its tax base and allowing it to further improve its quality. This cycle can lead to higher demand for its land, but because the municipality's boundaries are fixed, its number of inhabitants may become limited by factors like congestion or residents' preference for less density. At this upper bound, the increasing demand for land boosts the municipality’s tax revenue, and the municipality is able to select on only the wealthiest residents and highest productivity firms. This cycle continues, and the requirement for a balanced budget forces the municipality to spend this extra revenue on increasingly lower return projects. 

Now, consider a municipality that, due to its lower quality, experiences a decline in its population of inhabitants This decline can create a negative cycle, depending on the curvature of the municipal production function for quality. If there is an inverted U-shaped relationship, a decrease in size might move the municipality closer to an efficient scale, stopping the exodus due to a greater quality per capita. However, if the municipality is already at or below the efficient size, further decline only makes it less efficient. Observing the municipalities negative trajectory, inhabitants with the means leave the municipality. This moves the municipality further away from its optimal size, and leaves a negatively selected group of inhabitants still in the municipality. This low quality municipality has multiple high return projects available to it, but no means of executing those projects.    

In the first example with the high quality municipality, we see that the political constraints forcing municipalities to match their revenue with expenditures creates a market failure as municipalities pursue projects with lower and lower returns. From the perspective of the urban area, these funds would be better allocated to projects outside of the high quality municipality. This market failure is facilitated by the spatial and political constraint that the high quality urban area cannot expand its jurisdictional borders to find higher return projects. 

We can also see the market failure as a byproduct of imperfect competition. Associated with imperfect competition is the idea of market power. In the example, we can say that the municipality is expressing its market power through its ability to increase tax revenue while keeping a fixed number of inhabitants. For this to occur, the municipality must exclude additional residents and firms in order to provide the desired level of congestion and density to its inhabitants. In return for this exclusionary power, the inhabitants are willing to pay above the marginal cost of operating the municipality. Absent this exclusionary power stemming from imperfect competition, high quality municipalities would not be able to as effectively select on the wealthiest residents and most productive firms. This would result in a dispersion of these inhabitants into other municipalities, where their associated tax revenue could fund higher return projects. 

The market failure in the second example is a result of two forces: the curvature in the municipal production function and irreversible investment decisions. The curvature in the municipal production function directly leads to a welfare reduction due to the downward spiral it can create. To see the impact of irreversible investment decisions, consider that at one point in time, market forces induced the creation of the now low quality municipality. Then, due possibly to changes in transportation technology or consumer preferences, that same municipality is now sub-optimal. A locational decision that was made in that past has now dynamically become a source of market failure. Further, the institutional detail regarding the lack of municipal exit makes a rectifying this failure unlikely.






## Market Failure Targeting Interventions

In light of the market failures discussed above, one solution would be to enforce transfers from the high quality municipalities to the low quality municipalities. This approach would ensure that high-quality municipalities invest only in high-return projects, while low-quality municipalities receive the resources they need to improve their quality and reach an efficient scale of residents and firms. Even given that we were able to solve for the correct payment schedule, this intervention does not mitigate the market failure stemming from irreversible location decisions. Without addressing that issue, there will always be market failure, as even payments made to that municipality could have garnered higher return elsewhere.

 let a regulator of the urban area enforce such transfers, a role that we assumed the federal government would provide in the case of urban area competition. One practical, but not entirely satisfactory, reason is that urban areas do not always have access to such a regulator, as they often cross the predefined political boundaries of states and counties. A second, more fundamental issue is if a program of this type should even exist. A program attempting to implement such transfers would reduce incentives for the efficient production of quality in the high quality municipalities. There are also concerns about moral hazard, as transfers could incentivize poor management and reliance on the transfers. Further, a program of this type could entice residents and firms from high quality municipalities to exit the urban area all together. This is consistent with assumptions made, as the in flux of new, formally from a high quality municipality, residents and firms to an different urban area would represent a welfare improvement to that urban area. 

For this reason, we will restrict attention away from transfers as a possible intervention. This is not an restriction without support. First, as described above, the curvature in the municipal production function makes determining the correct allocations complex. Second, these transfers are likely to be politically unfeasible.  Enacting such a program would be undesirable from the residents and firms of the high quality municipality. This group can typically be assumed to carry more political cache than the group representing the low quality municipalities. Third, transfers do not address the market failures stemming from dynamics.


Having ruled away transfers as an intervention, we can now look to alter the institutional details that lead to the market inefficiency. To begin, we could allow municipalities to run surpluses and deficits. This alleviates the issue of high quality municipalities spending on low return projects, but raises the question of what will happen to those funds if they are not being used. Abstracting from the nefarious, corruption, solution, we could imagine that these funds would be placed into some reserve, allowing the municipality a safeguard against future risk. But this risk mitigation opens another avenue for competition, as residents and firms desire a municipality that is able to protect their investment from negative shocks. This results in the same market inefficiency, but instead of spending on low return projects, municipalities are overspending on inefficient risk mitigation.

On the other side, allowing low quality municipalities to run deficits would allow for additional quality production. However, even as each additional borrowed dollar contributes to the physical production of quality, it also increases the risk for the municipality. This creates an adverse selection problem, as only the least risk adverse firms and residents will be willing to invest in a leveraged municipality. This leads to a municipality that is highly unresistant to negative shocks, which can also be viewed as a market inefficiency.  

Allowing expanded jurisdictions along with municipal exit could solve the market inefficiencies, but is unlikely to work given the spatial nature of municipal competition, something we unfortunately cannot alter. To see this, we can view the problem simply as high quality municipalities not possessing enough land, and low quality municipalities possessing too much. A land trade between the two would work like a cash transfer, minus the complexity, and represent a solution to the market inefficiency. However, the spatial dimension of competition in the urban area can hamper this process, and the possible presence of spillover effects make this coincidence of wants even less likely. A reasonable restriction to place on municipalities expanding their jurisdictions would be that they must remain connected. So to make the market inefficiency correcting trade as above, we would require a space constrained high quality municipality to share a boundary with a space-overwhelmed low quality municipality. Spillover effects make this situation unlikely. Consider the first situation above, the high quality municipality's spending on projects creates amenities and a pool of wealthy consumers that are not easily excluded from residents and firms of nearby municipalities. As this investment spills over into neighboring municipalities, their quality increases, isolating the high quality municipality from a low quality merge partner. We can view this as the high quality municipality producing a positive externality, known to inhibit the implementation of the Fundamental Welfare Theorems. 

Now consider the second situation. The low quality municipality is losing residents and firms. Neighboring municipalities have a marginally more difficult time attracting firms because they could locate to a similar municipality that neighbors a municipality with wealthy residents. They also have a marginally more difficult time attracting residents because again, they could locate in a similar municipality that neighbors a municipality with high amenities. This also has the effect of isolating the struggling municipality from a merge partner, and can be viewed as the low quality municipality producing a negative externality.

Taking the assumptions above that rule out other interventions, we find that our policy levers are close to exhausted. Remaining interventions involve either merging smaller municipalities together in an attempt to allow them access to economies of scale, or breaking up larger municipalities into the optimally sized parts. We will again assume that the second of those options is politically unfeasible. This leaves us with examining municipal mergers.  


# Reduced Form Evidence of Municipal Market Failures


# Data and the St. Louis Metropolitan Area


# Dynamic Model of an Urban Area


# Results

# Counterfactual Mergers

# Conclusion




## Municipal Spatial Inefficiencies 


## Municipal Mergers

Municipal mergers, the process of merging two or more political jurisdictions in an urban area, are often discussed in economic planning initiatives. 


(1) ] LANCASTER, K.: Variety, Equity and Efficiency. New York: Columbia University Press, 1979.

























