---
title: "Replication"
output: html_document
---
```{r,echo = F}
base_dir = getwd()
base_url = paste0("https://",substr(base_dir,8, nchar(base_dir)))
wp_link = paste0(base_url,"/WorkingPaper.html")
ws_link = paste0(base_url,"/WorkingSlides.html")
rep_link = paste0(base_url,"/Replication.html")
miniblog_link = paste0(base_url,"/MiniBlog.html")
```

[Home](https://chasewiedemann.github.io/index.html) |
[Projects](https://chasewiedemann.github.io/Site/Projects/projects.html) |
[Blog](https://chasewiedemann.github.io/Site/blog.html) |

[Working Paper](`r wp_link`)|
[Working Slides](`r ws_link`)|
[Replication](`r rep_link`)|


# Introduction

The winners and losers of economic competition are not evenly distributed across geographic space. This holds, almost as a rule, regardless of the scope in which the geographic space is defined. Starting with the scope of the national economy, at any point in time, competition between urban area bestows economic growth on the winners while leaving economic stagnation or even decay to the losers. Viewing a single urban area, the same can be said of the many municipalities that make up the urban area: the most competitive of the municipalities receive the bulk of the good fortune, while the less competitive are left behind. This multitude of outcomes within a scope presents interesting incentives and welfare calculations: a municipalities fortune is tied not only to its competitive position among the municipalities in its urban area, but also to the competitive position of its urban area within the national market. Stated simply, a municipality will not be able to compete for residents and firms unless residents and firms are willing to locate in that urban area. This forces municipalities to view their competitors not only as strategic substitutes and as strategic complements. Further, because of the close geographical proximity of municipal competition, both positive and negative spillovers are likely to be present. 

A large literature starting with Cooper \& John (1988) discusses how economies that display spillovers and strategic complementarity can often be met with coordination failures. Where coordination failures in this context can be described as the availability of an equilibrium that provides greater returns to all municipalities, but no individual municipality has the incentive to deviate to this strategy. These coordination failures motivate the policy prescription investigated in this paper, municipal mergers.

The sources of coordination and market failure can be separated into three broad classifications. First, the spatial nature of municipal competition requires that municipalities compete in close geographic proximity. Second, political constraints on municipalities can be a source of coordination failure. These constraints include legally mandated balanced budgets, fixed jurisdictional boundaries, and rare municipal exit. Third, coordination failures can also be a result of dynamics, as durable investment decisions made in the past can reinforce the existing equilibrium.

As stated above, this paper investigates municipal mergers, or the process of merging one or more political entities into one, as a possible policy intervention to select a higher welfare equilibrium. Such a heavy-handed policy instrument is shown to be needed through a process of elimination. Alternative policy interventions, such as transfers, removing the restriction of balanced budgets, collective setting of property tax rates, and allowing municipal exit and expansion, are examined. We contend that these alternatives either do not solve the coordination problem, do not correct a market failure, or even lead to new sources of inefficiency.

Municipal mergers are not a new concept in policy debates surrounding municipalities, but the explicit framing as a mechanism to select higher economic activity equilibrium can be seen as a contribution. Previous arguments in favor of municipal mergers rely on the expected benefits from access to greater economies of scale and more effective regional planning. Detractors counter these claims with the perceived negative effects of decreased constituent attachment to the political process and congestion effects. A large academic literature has tried to add to this debate by investigating past municipal mergers in either the reduced form or through differences in differences identification strategies. This literature has led to mixed results, which possibly can be attributed to the difficulties of examining municipal mergers without an explicit framework surrounding the incentives of the urban area as a whole. 


# Municipal Competition

To highlight the main mechanics that generate ranked equilibria, we begin with a simplified model with symmetric municipalities based  on Cooper \& John (1988). Let an urban area be modeled as the joint production of a public good by the $M$ municipalities. Let $e_i \in [0,E]$ be the effort of municipality $i$ in the production of the public good $c$. The production function is $c = f(e_i,\overline e)$ when municipality $i$ chooses $e_i$ and the other (symmetric) municipalities choose $\overline e$. The production function is increasing in both arguments.  All municipalities share a common quasi-concave utility function define over consumption of the public good and effort $U(c,e)$ where municipalities enjoy the public good and dislike effort. Let the payoff function for municipality $i$ be given as

$$ V(e_i,\overline e) = U(f(e_i,\overline e),e_i) $$

Now, differentiate the payoff function by $e_i$ and $\overline e$ to yield

$$ V_{12} =  U_1f_{12} + U_{11}f_1f_2 + U_{12}f_2 $$

This is the resulting payoff to municipality $i$ if they increase their effort when all other municipalities increase their effort. The sign of this term will determine whether municipalities view their competitors as either strategic complements ($V_{12} >0$) or substitutes ($V_{12} <0$). For now, assume that the utility is separable in consumption and effort ($U_{12} = 0$).  Notice that the second term is unambiguously non-positive. The first derivatives of $f$ are always positive, the utility function is quasi-concave so $U_{11} \leq 0$. The first term contains $U_1$ which is also ambiguously positive. The key term is then $f_{12}$, which captures the complementarity of effort in the production process. A necessary condition is that $f_{12} >0$, and in general we need that these complementarities are large relative to the concavity of the utility function to ensure strategic complementarity among municipalities.

The slope of municipality $i$'s reaction 



# Municipal Market Failure, Policy Interventions, and Municipal Mergers

## Municipal Market Failures

Certain institutional details regarding municipalities suggest that market failures are likely to occur. First, municipal budgets are legislatively enforced to be balanced. Second, municipal boundaries are generally fixed at the time of incorporation and rarely change. Third, municipalities typically do not have the option to exit the market. Finally, municipalities can only enter at the outskirts of an urban area, which causes existing municipalities to become "landlocked". We consider two leading examples to center the discussion of municipal market failures around.

First, consider a high-quality municipality. Its appeal attracts firms and residents (refered to jointly as inhabitants), expanding its tax base and allowing it to further improve its quality. This cycle can lead to higher demand for its land, but because the municipality's boundaries are fixed, its number of inhabitants may become limited by factors like congestion or residents' preference for less density. At this upper bound, the increasing demand for land boosts the municipality’s tax revenue, and the municipality is able to select on only the wealthiest residents and highest productivity firms. This cycle continues, and the requirement for a balanced budget forces the municipality to spend this extra revenue on increasingly lower return projects. 

Now, consider a municipality that, due to its lower quality, experiences a decline in its population of inhabitants This decline can create a negative cycle, depending on the curvature of the municipal production function for quality. If there is an inverted U-shaped relationship, a decrease in size might move the municipality closer to an efficient scale, stopping the exodus due to a greater quality per capita. However, if the municipality is already at or below the efficient size, further decline only makes it less efficient. Observing the municipalities negative trajectory, inhabitants with the means leave the municipality. This moves the municipality further away from its optimal size, and leaves a negatively selected group of inhabitants still in the municipality. This low quality municipality has multiple high return projects available to it, but no means of executing those projects.    

In the first example with the high quality municipality, we see that the political constraints forcing municipalities to match their revenue with expenditures creates a market failure as municipalities pursue projects with lower and lower returns. From the perspective of the urban area, these funds would be better allocated to projects outside of the high quality municipality. This market failure is facilitated by the spatial and political constraint that the high quality urban area cannot expand its jurisdictional borders to find higher return projects. 

We can also see the market failure as a byproduct of imperfect competition. Associated with imperfect competition is the idea of market power. In the example, we can say that the municipality is expressing its market power through its ability to increase tax revenue while keeping a fixed number of inhabitants. For this to occur, the municipality must exclude additional residents and firms in order to provide the desired level of congestion and density to its inhabitants. In return for this exclusionary power, the inhabitants are willing to pay above the marginal cost of operating the municipality. Absent this exclusionary power stemming from imperfect competition, high quality municipalities would not be able to as effectively select on the wealthiest residents and most productive firms. This would result in a dispersion of these inhabitants into other municipalities, where their associated tax revenue could fund higher return projects. 

The market failure in the second example is a result of two forces: the curvature in the municipal production function and irreversible investment decisions. The curvature in the municipal production function directly leads to a welfare reduction due to the downward spiral it can create. To see the impact of irreversible investment decisions, consider that at one point in time, market forces induced the creation of the now low quality municipality. Then, due possibly to changes in transportation technology or consumer preferences, that same municipality is now sub-optimal. A locational decision that was made in that past has now dynamically become a source of market failure. Further, the institutional detail regarding the lack of municipal exit makes a rectifying this failure unlikely.






## Market Failure Targeting Interventions

In light of the market failures discussed above, one solution would be to enforce transfers from the high quality municipalities to the low quality municipalities. This approach would ensure that high-quality municipalities invest only in high-return projects, while low-quality municipalities receive the resources they need to improve their quality and reach an efficient scale of residents and firms. Even given that we were able to solve for the correct payment schedule, this intervention does not mitigate the market failure stemming from irreversible location decisions. Without addressing that issue, there will always be market failure, as even payments made to that municipality could have garnered higher return elsewhere.

 let a regulator of the urban area enforce such transfers, a role that we assumed the federal government would provide in the case of urban area competition. One practical, but not entirely satisfactory, reason is that urban areas do not always have access to such a regulator, as they often cross the predefined political boundaries of states and counties. A second, more fundamental issue is if a program of this type should even exist. A program attempting to implement such transfers would reduce incentives for the efficient production of quality in the high quality municipalities. There are also concerns about moral hazard, as transfers could incentivize poor management and reliance on the transfers. Further, a program of this type could entice residents and firms from high quality municipalities to exit the urban area all together. This is consistent with assumptions made, as the in flux of new, formally from a high quality municipality, residents and firms to an different urban area would represent a welfare improvement to that urban area. 

For this reason, we will restrict attention away from transfers as a possible intervention. This is not an restriction without support. First, as described above, the curvature in the municipal production function makes determining the correct allocations complex. Second, these transfers are likely to be politically unfeasible.  Enacting such a program would be undesirable from the residents and firms of the high quality municipality. This group can typically be assumed to carry more political cache than the group representing the low quality municipalities. Third, transfers do not address the market failures stemming from dynamics.


Having ruled away transfers as an intervention, we can now look to alter the institutional details that lead to the market inefficiency. To begin, we could allow municipalities to run surpluses and deficits. This alleviates the issue of high quality municipalities spending on low return projects, but raises the question of what will happen to those funds if they are not being used. Abstracting from the nefarious, corruption, solution, we could imagine that these funds would be placed into some reserve, allowing the municipality a safeguard against future risk. But this risk mitigation opens another avenue for competition, as residents and firms desire a municipality that is able to protect their investment from negative shocks. This results in the same market inefficiency, but instead of spending on low return projects, municipalities are overspending on inefficient risk mitigation.

On the other side, allowing low quality municipalities to run deficits would allow for additional quality production. However, even as each additional borrowed dollar contributes to the physical production of quality, it also increases the risk for the municipality. This creates an adverse selection problem, as only the least risk adverse firms and residents will be willing to invest in a leveraged municipality. This leads to a municipality that is highly unresistant to negative shocks, which can also be viewed as a market inefficiency.  

Allowing expanded jurisdictions along with municipal exit could solve the market inefficiencies, but is unlikely to work given the spatial nature of municipal competition, something we unfortunately cannot alter. To see this, we can view the problem simply as high quality municipalities not possessing enough land, and low quality municipalities possessing too much. A land trade between the two would work like a cash transfer, minus the complexity, and represent a solution to the market inefficiency. However, the spatial dimension of competition in the urban area can hamper this process, and the possible presence of spillover effects make this coincidence of wants even less likely. A reasonable restriction to place on municipalities expanding their jurisdictions would be that they must remain connected. So to make the market inefficiency correcting trade as above, we would require a space constrained high quality municipality to share a boundary with a space-overwhelmed low quality municipality. Spillover effects make this situation unlikely. Consider the first situation above, the high quality municipality's spending on projects creates amenities and a pool of wealthy consumers that are not easily excluded from residents and firms of nearby municipalities. As this investment spills over into neighboring municipalities, their quality increases, isolating the high quality municipality from a low quality merge partner. We can view this as the high quality municipality producing a positive externality, known to inhibit the implementation of the Fundamental Welfare Theorems. 

Now consider the second situation. The low quality municipality is losing residents and firms. Neighboring municipalities have a marginally more difficult time attracting firms because they could locate to a similar municipality that neighbors a municipality with wealthy residents. They also have a marginally more difficult time attracting residents because again, they could locate in a similar municipality that neighbors a municipality with high amenities. This also has the effect of isolating the struggling municipality from a merge partner, and can be viewed as the low quality municipality producing a negative externality.

Taking the assumptions above that rule out other interventions, we find that our policy levers are close to exhausted. Remaining interventions involve either merging smaller municipalities together in an attempt to allow them access to economies of scale, or breaking up larger municipalities into the optimally sized parts. We will again assume that the second of those options is politically unfeasible. This leaves us with examining municipal mergers.  


# Reduced Form Evidence of Municipal Market Failures


# Dynamic Model of an Urban Area


# Results

# Municipal Mergers in the St. Louis Metropolitan Area

# Conclusion













